version: '3.8'
services:
  develop:
    image: node
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /data
    working_dir: /data
    user: "${UID}:${GID}"
    command: npm run develop -- --host 0.0.0.0
