# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build --if-presen
    - run: npx gh-pages -d public -u "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -r "https://git:${{ github.token }}@github.com/${{ github.repository }}.git"
