# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn
    - run: yarn build --if-presen
    - run: mkdir -p -m 700 ~/.ssh && install -m 0600 /dev/null ~/.ssh/id && echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id
    - run: yarn -s run gh-pages -d .docz/public -u "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -p "https://${github.token}@github.com/${{ github.repository }}.git"
